import type { Metadata } from 'next'
import './globals.css'
import Navbar from '@/component/navbar/Navbar'
import Footer from '@/component/footer/Footer'
// import { Inter, DM_Sans } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })
// const dmSans = DM_Sans({ subsets: ['latin'] })
// ${dmSans.className}
export const metadata: Metadata = {
     title: 'Create Next App',
     description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
     return (
          <html lang='en'>
               <body>
                    <Navbar />
                    {children}
                    <Footer />
               </body>
          </html>
     )
}
